blank_issues_enabled: false
contact_links: []
pull_request_templates:
  - name: "ğŸ“‹ ê¸°ëŠ¥ ì¶”ê°€/ë³€ê²½"
    description: "ê¸°ëŠ¥ ì¶”ê°€/ë³€ê²½ì„ ê¸°ë¡í•  ë•Œ ì‚¬ìš©í•˜ì„¸ìš”."
    file: "feat.md"
  - name: "ğŸ› ï¸ ë²„ê·¸ í•´ê²°"
    description: "ë²„ê·¸ë¥¼ ì–´ë–»ê²Œ í•´ê²°í–ˆëŠ”ì§€ ê¸°ë¡í•˜ì„¸ìš”."
    file: "bug_fix.md"