blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: ğŸ“‹ ì‘ì—…(Task)
    description: ì¼ë°˜ì ì¸ ì‘ì—… í•­ëª©ì„ ê¸°ë¡í•  ë•Œ ì‚¬ìš©í•˜ì„¸ìš”.
    file: task.md
  - name: ğŸ› ï¸ ë²„ê·¸ ë¦¬í¬íŠ¸
    description: ë²„ê·¸ë¥¼ ì–´ë–»ê²Œ í•´ê²°í–ˆëŠ”ì§€ ê¸°ë¡í•˜ì„¸ìš”.
    file: bug_report.md
